### ISSUE TITLE
Can't build project.

### ISSUE THREAD

**Issue by bishwash72** [MarcelloLins/Apple-Store-Crawler#1]
**Can't build project :**
Can't find package WebUtilsLib version 2.2.3 as well well as some other packages. I tried copying dependencies from PlayStoreCrawler project but it didn't worked. 
<package id="WebUtilsLib" version="2.2.3" targetFramework="net45" />

__ERROR MESSAGE__
Error	3	The type or namespace name 'WebUtilsLib' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\bish\Desktop\appstore\Apple-Store-Crawler-master\AppStoreCrawler\SharedLibrary\RequestsHandler.cs	6	7	SharedLibrary

**Comment by MarcelloLins** [comment]
This was caused because the WebUtilsLib (which is a wrapper I wrote for HTTP Requests) is on a private nuget repo instead on a public one.

I've made a local copy of the DLL on a folder and referenced that instead.

Pull the updates and let me know if it fixed the problem.

**Comment by bishwash72** [comment]
It worked. I copied other dependencies from PlayStoreCrawler project.
